#!/usr/bin/env bash
# setup-voice-input.sh — Install and configure the voice input system
# Usage: ./setup-voice-input.sh [OPTIONS]
# See --help for full options.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"
# shellcheck source=lib/config-validator.sh
source "${SCRIPT_DIR}/lib/config-validator.sh"
# shellcheck source=lib/prerequisites.sh
source "${SCRIPT_DIR}/lib/prerequisites.sh"

# ─── Defaults ─────────────────────────────────────────────────────────────────

TOOL="superwhisper"
MODEL="large-v3"
SHORTCUT="RightCommand"
ACTIVATION_MODE="push_to_talk"
CLEANUP_TIER="rules"
OFFLINE_ONLY="true"
SILENCE_TIMEOUT_MS="1500"
MAX_RECORDING_DURATION_S="300"
LANGUAGE="en"
DRY_RUN=false

# ─── Usage ────────────────────────────────────────────────────────────────────

usage() {
  cat <<'EOF'
Usage: setup-voice-input.sh [OPTIONS]

Install and configure the voice input system on a macOS host.

Options:
  --tool <name>           Voice tool: superwhisper (default), voiceink
  --model <size>          Whisper model: tiny, base, small, medium, large-v3 (default), turbo
  --shortcut <key>        Push-to-talk key: RightCommand (default), RightOption, Fn, etc.
  --cleanup-tier <tier>   Cleanup level: none, rules (default), local_llm, cloud
  --offline-only          Restrict to local-only processing (default: enabled)
  --no-offline            Allow network-based processing
  --dry-run               Show what would be configured without making changes
  --help                  Show this help message

Examples:
  # Default setup with Superwhisper
  ./setup-voice-input.sh

  # Use VoiceInk with medium model
  ./setup-voice-input.sh --tool voiceink --model medium

  # Enable local LLM cleanup via Ollama
  ./setup-voice-input.sh --cleanup-tier local_llm

  # Preview what would be created
  ./setup-voice-input.sh --dry-run

Exit Codes:
  0  Success
  1  General error
  2  Missing prerequisite (tool not installed)
  3  Invalid configuration
  4  Platform not supported (not macOS)
EOF
}

# ─── Argument Parsing ─────────────────────────────────────────────────────────

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --tool)
        TOOL="${2:-}"
        shift 2
        ;;
      --model)
        MODEL="${2:-}"
        shift 2
        ;;
      --shortcut)
        SHORTCUT="${2:-}"
        shift 2
        ;;
      --cleanup-tier)
        CLEANUP_TIER="${2:-}"
        shift 2
        ;;
      --offline-only)
        OFFLINE_ONLY="true"
        shift
        ;;
      --no-offline)
        OFFLINE_ONLY="false"
        shift
        ;;
      --dry-run)
        DRY_RUN=true
        shift
        ;;
      --help | -h)
        usage
        exit 0
        ;;
      *)
        log_error "Unknown option: $1"
        usage
        exit "$EXIT_GENERAL_ERROR"
        ;;
    esac
  done
}

# ─── Validation ───────────────────────────────────────────────────────────────

validate_args() {
  local errors=0

  validate_option "tool" "$TOOL" "${VALID_TOOLS[@]}" || errors=$((errors + 1))
  validate_option "model" "$MODEL" "${VALID_MODELS[@]}" || errors=$((errors + 1))
  validate_option "cleanup-tier" "$CLEANUP_TIER" "${VALID_CLEANUP_TIERS[@]}" || errors=$((errors + 1))
  validate_shortcut "$SHORTCUT" || errors=$((errors + 1))

  # Cross-field: offline + cloud conflict
  if [[ "$OFFLINE_ONLY" == "true" ]] && [[ "$CLEANUP_TIER" == "cloud" ]]; then
    log_error "Cannot use --cleanup-tier=cloud with --offline-only (default)"
    log_info "Use --no-offline to allow cloud processing"
    errors=$((errors + 1))
  fi

  if ((errors > 0)); then
    return "$EXIT_INVALID_CONFIG"
  fi
  return 0
}

# ─── Settings File Generation ─────────────────────────────────────────────────

generate_settings() {
  local output_file="${VOICE_INPUT_SETTINGS}"

  cat > "$output_file" <<EOF
# Voice Input Settings
# Generated by setup-voice-input.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Schema: specs/015-voice-input/contracts/config-schema.yaml

tool: ${TOOL}
whisper_model: ${MODEL}
activation_shortcut: ${SHORTCUT}
activation_mode: ${ACTIVATION_MODE}
offline_only: ${OFFLINE_ONLY}
cleanup_tier: ${CLEANUP_TIER}
EOF

  # Conditional cleanup fields
  if [[ "$CLEANUP_TIER" == "local_llm" ]]; then
    echo "cleanup_local_llm_model: phi3:mini" >> "$output_file"
  fi

  if [[ "$CLEANUP_TIER" == "cloud" ]]; then
    echo "cleanup_cloud_provider: claude" >> "$output_file"
    echo "cleanup_cloud_api_key_env: ANTHROPIC_API_KEY" >> "$output_file"
  fi

  cat >> "$output_file" <<EOF
custom_vocab_paths:
  - ~/.config/voice-input/vocabulary.yaml
silence_timeout_ms: ${SILENCE_TIMEOUT_MS}
max_recording_duration_s: ${MAX_RECORDING_DURATION_S}
language: ${LANGUAGE}
output_method: clipboard
visual_feedback: true
EOF

  log_success "Created settings: $output_file"
}

# ─── File Deployment ──────────────────────────────────────────────────────────

deploy_vocabulary() {
  local seed_file="${SCRIPT_DIR}/../config/vocabulary.yaml"
  local target_file="${VOICE_INPUT_VOCABULARY}"

  if [[ -f "$target_file" ]]; then
    log_info "Vocabulary file already exists, skipping: $target_file"
    return 0
  fi

  if [[ -f "$seed_file" ]]; then
    cp "$seed_file" "$target_file"
    log_success "Created vocabulary: $target_file"
  else
    log_warn "Seed vocabulary not found at $seed_file"
  fi
}

deploy_cleanup_prompt() {
  local seed_file="${SCRIPT_DIR}/../config/ai-cleanup-prompt.txt"
  local target_file="${VOICE_INPUT_CLEANUP_PROMPT}"

  if [[ -f "$seed_file" ]]; then
    cp "$seed_file" "$target_file"
    log_success "Created cleanup prompt: $target_file"
  else
    log_warn "AI cleanup prompt not found at $seed_file"
  fi
}

# ─── Dry Run ──────────────────────────────────────────────────────────────────

print_dry_run() {
  echo ""
  echo "=== Dry Run: Would perform the following ==="
  echo ""
  echo "Configuration:"
  echo "  Tool:            $TOOL"
  echo "  Model:           $MODEL"
  echo "  Shortcut:        $SHORTCUT"
  echo "  Activation:      $ACTIVATION_MODE"
  echo "  Cleanup Tier:    $CLEANUP_TIER"
  echo "  Offline Only:    $OFFLINE_ONLY"
  echo "  Language:        $LANGUAGE"
  echo ""
  echo "Files to create:"
  echo "  ${VOICE_INPUT_CONFIG_DIR}/"
  echo "  ├── settings.yaml"
  if [[ ! -f "$VOICE_INPUT_VOCABULARY" ]]; then
    echo "  ├── vocabulary.yaml"
  else
    echo "  ├── vocabulary.yaml (exists, skipped)"
  fi
  echo "  └── ai-cleanup-prompt.txt"
  echo ""
  echo "No changes made."
}

# ─── Tool-Specific Guidance ──────────────────────────────────────────────────

print_superwhisper_guidance() {
  echo ""
  echo "=== Superwhisper Configuration ==="
  echo ""
  echo "Complete setup in Superwhisper:"
  echo ""
  echo "1. Model Setup:"
  echo "   • Open Superwhisper → Settings → Models"
  echo "   • Download the '${MODEL}' model (recommended for 95%+ accuracy)"
  echo "   • Select it as the active model"
  echo ""
  echo "2. Shortcut Setup:"
  echo "   • Go to Settings → Shortcuts"
  echo "   • Set Push-to-Talk to: ${SHORTCUT}"
  echo "   • Mode: Hold to record, release to transcribe"
  echo ""
  echo "3. Dictation Mode:"
  echo "   • Go to Settings → Modes"
  echo "   • Select 'Code Dictation' mode (or create custom)"
  echo "   • Enable 'Auto-copy to clipboard'"
  echo ""
  echo "4. Privacy:"
  echo "   • Ensure 'Process locally' is enabled"
  echo "   • Disable any cloud transcription options"
  echo ""
  echo "Verify setup: ./verify-voice-input.sh"
}

print_voiceink_guidance() {
  echo ""
  echo "=== VoiceInk Configuration ==="
  echo ""
  echo "Complete setup in VoiceInk:"
  echo ""
  echo "1. Model Setup:"
  echo "   • Open VoiceInk → Settings → Transcription"
  echo "   • Download the '${MODEL}' model"
  echo "   • Select it as the active model"
  echo ""
  echo "2. Shortcut Setup:"
  echo "   • Go to Settings → Hotkey"
  echo "   • Set activation key to: ${SHORTCUT}"
  echo "   • Mode: Push-to-talk (hold to record)"
  echo ""
  echo "3. Output:"
  echo "   • Enable 'Copy to clipboard' in output settings"
  echo ""
  echo "4. Privacy:"
  echo "   • Ensure all processing is set to 'On-device'"
  echo ""
  echo "Verify setup: ./verify-voice-input.sh"
}

print_tool_guidance() {
  case "$TOOL" in
    superwhisper)
      print_superwhisper_guidance
      ;;
    voiceink)
      print_voiceink_guidance
      ;;
  esac
}

# ─── Main ─────────────────────────────────────────────────────────────────────

main() {
  parse_args "$@"

  # Validate arguments
  validate_args || exit $?

  # Dry run mode
  if [[ "$DRY_RUN" == true ]]; then
    print_dry_run
    exit "$EXIT_SUCCESS"
  fi

  echo ""
  echo "=== Voice Input Setup ==="
  echo ""

  # Check prerequisites (skip if VOICE_INPUT_SKIP_PREREQS is set, for testing)
  if [[ -z "${VOICE_INPUT_SKIP_PREREQS:-}" ]]; then
    check_macos || exit "$EXIT_PLATFORM_NOT_SUPPORTED"
    check_apple_silicon || log_warn "Apple Silicon recommended for optimal performance"
    check_tool_installed "$TOOL" || exit "$EXIT_MISSING_PREREQUISITE"
  fi

  # Create config directory
  ensure_dir "$VOICE_INPUT_CONFIG_DIR"

  # Generate settings
  generate_settings

  # Deploy vocabulary
  deploy_vocabulary

  # Deploy cleanup prompt
  deploy_cleanup_prompt

  # Validate generated settings
  if validate_settings "$VOICE_INPUT_SETTINGS" 2>/dev/null; then
    log_success "Settings validation passed"
  else
    log_error "Generated settings failed validation"
    exit "$EXIT_INVALID_CONFIG"
  fi

  # Print tool-specific guidance
  print_tool_guidance

  echo ""
  log_success "Setup complete! Configure ${TOOL} per the instructions above."
}

main "$@"
